### ISSUE TITLE
sklearn and joblib outdated

### ISSUE THREAD

**Issue by Stephen-Strosko** [QuantGov/quantgov#79]
C:\Users\Steve\Desktop\federal_register_estimator>python scripts/vectorize_trainers.py -o data/trainers --vectorizer_outfile data/vectorizer ../federal_register
C:\Users\Steve\AppData\Local\Continuum\miniconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)

https://stackoverflow.com/questions/61893719/importerror-cannot-import-name-joblib-from-sklearn-externals

**Comment by jnelson16** [comment]
This needs to be fixed in https://github.com/QuantGov/estimator, not here.
